# Generated by Django 6.0.5 on 2026-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_books', to='login_app.user'),
        ),
    ]
